version: '3.9'
services:
  app:
    container_name: userservice-api
    image: user-service:0.0.1
    build: ./
    ports:
      - '8001:8001'
    depends_on:
      - postgres


  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data:
